name: lint

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 16 * *'
  push:
    branches:
      - main
      - dev
    paths:
      - '**.sh'
      - '.github/workflows/**'
      - '.github/actionlint.yaml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '**.sh'
      - '.github/workflows/**'
      - '.github/actionlint.yaml'

permissions:
  contents: read

env:
  ACTION_LINT_VERSION: "1.7.12"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.10.0
        env:
          SHFMT_OPTS: --simplify --keep-padding
        with:
          sh_checker_checkbashisms_enable: true
          sh_checker_shfmt_disable: true

      - name: Install action-lint
        env:
          LINT_VERSION: ${{ env.ACTION_LINT_VERSION }}
          REMOTE_URL: "https://raw.githubusercontent.com/rhysd/actionlint/v${{ env.ACTION_LINT_VERSION }}/scripts/download-actionlint.bash"
        run: |
          INSTALL_DIR="${HOME}/.local/bin"
          mkdir -p "$INSTALL_DIR"
          curl -sfL \
            --retry 3 \
            --retry-delay 5 \
            --connect-timeout 15 \
            --max-time 60 \
            "$REMOTE_URL" | bash -s -- "$LINT_VERSION" "$INSTALL_DIR"
          echo "$INSTALL_DIR" >> "$GITHUB_PATH"

      - name: Lint GitHub Actions workflows
        run: |
          shellcheck --version
          find .github/workflows -type f \( -name "*.yml" -o -name "*.yaml" \) -exec actionlint -color -pyflakes= {} +
          echo "Linting finished."
